version: '3.4'

services:
  db:
    container_name: 'vuels_db'
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "33006:3306"
    volumes:
      - ./containers/mysql_data:/var/lib/mysql
    command: --innodb-use-native-aio=0
  nginx:
    container_name: 'vuels_nginx'
    build: ./nginx
    command: >
      /bin/bash -c
      "envsubst '$$NGINX_SERVER_NAME $$NGINX_SERVER_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    environment:
      - TZ=Asia/Tokyo
      - NGINX_SERVER_NAME=dev.vuels.jp
      - NGINX_SERVER_PORT=80
    ports:
      - 80:80
      - 443:443
    volumes:
      - tmp:/web/app/tmp
      - public:/web/app/public
    depends_on:
      - web
  web:
    container_name: 'vuels_web'
    build:
      context: .
      args:
        ASSETS_PRECOMPILE: 'false'
    environment:
      RAILS_ENV: development
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: vuels_development
      USER_OTP_SECRET: 7148baed8c4681f27dd6dba7b90acf976427d21f5b8ca06d2cac206cf1eb14e85eb17c4957bcc72061d948f0a181d2aa5b472c6ad59c525d2238012e2b6d63bb
    command: sh -c "rm -f  /web/app/tmp/pids/server.pid && bundle exec rails s"
    tty: true
    stdin_open: true
    volumes:
      - ./web:/web/app
      - bundle:/usr/local/bundle
      - tmp:/web/app/tmp
      - public:/web/app/public
    links:
      - db
volumes:
  mysql_data:
  bundle:
  tmp:
  public: